spring.application.name=graphtest

# Spring
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.orm.connections.pooling=ERROR
spring.sql.init.mode=always
spring.output.ansi.enabled=ALWAYS
spring.jpa.show-sql=false
spring.web.error.include-exception=false

# Documentation
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# Banco Relacional
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# Banco Orientado a Grafos
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
spring.data.neo4j.database=${NEO4J_DATABASE}


# Seguranca
jwt.segredo=${JWT_SEGREDO}
jwt.tempo_expiracao=${JWT_TEMPO_EXPIRACAO}
