spring.application.name=graphtest

# Spring
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.orm.connections.pooling=ERROR
spring.sql.init.mode=always
spring.output.ansi.enabled=ALWAYS
spring.jpa.show-sql=false
spring.web.error.include-exception=false

# Documentation
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/graphtest
spring.datasource.username=postgres
spring.datasource.password=root

# Seguranca
jwt.segredo=tfSMug9virNllOllGWd7t1q85VjYSFvN0zB5bSW5M15
jwt.tempo_expiracao=86400000
